version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=qbox
  redis:
    image: redis:latest
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - "6379:6379"
      
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/grafana-datasource.yml
    ports:
      - "3000:3000"
